telegram:
  api-url: https://api.telegram.org/
  bot-name: ${BOT_NAME}
  bot-token: ${BOT_TOKEN}
  webhook-path: ${WEBHOOK_PATH}
  bot-username: ${BOT_USERNAME}

server:
  port: ${SERVER_PORT}
  error:
    include-message: always
  data:
    mongodb:
      uri: ${MONGODB_URI}